Issue 30 criar entidade classe cliente no sistema de veículos
iftopalmas/sistemas-viagens pull request #38
Opened 2022-11-22 12:40 UTC by BernardCarvalho

# close #30

2022-11-22 12:55 UTC, manoelcampos commented
Pensa nos atributos. Não coloquei porque não deu tempo 🤣 
Vou atualizar lá na página da issue.

2022-11-22 16:26 UTC, BernardCarvalho commented
Endereco

logradouro: String @NotNull @NotBlank
cep: String @NotNull @NotBlank
cidade: **Cidade** @NotNull **@NotBlank**

Boa tarde professor, é necessário o uso da notação NotBlank em um objeto do tipo Cidade?

Imagino que talvez o atributo cidade possa ser do tipo String.

Aguardo o posicionamento do gerente de projetos.

2022-11-22 17:39 UTC, manoelcampos commented
> Boa tarde professor, é necessário o uso da notação NotBlank em um objeto do tipo Cidade?
> Imagino que talvez o atributo cidade possa ser do tipo String.

NotBlank é só pra String. O atributo é do tipo Cidade mesmo. Foi erro de ctrl+c e ctrl+v 🤣

2022-11-22 17:55 UTC, manoelcampos commented
> Entendido, pelo que verifiquei no merge conflict, é só que o git entendeu que estamos editando uma mesma dependencia, no entanto tratam-se de dependencias distintas, e que portanto, deveriam ser ambas acrescentadas ao arquivo final, me coloco a disposição para ir ao senhor verificar como resolver esse merge conflict, mas imagino que seja apenas aceitar ambas as versões, concatenando-as.

Sim, o problema é que possivelmente em PR distintas, cada uma adicionou uma dependência diferente, mas as duas foram adicionadas no mesmo exato local do pom. Aí gerou o conflito. O git não tem como decidir sozinho se é pra deixar as duas, se apenas a 1a ou apenas a 2a. Neste caso, seria deixar as duas mesma. No IntelliJ, na tela de resolução de merge te permite fazer isso apenas clicando nuns botões.

Ele mostra o conflito no pom como:

```diff
<<<<<<< issue_30-criar-entidade-classe-cliente-no-sistema-de-veículos

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-validation</artifactId>
=======
		<dependency>
			<groupId>org.springdoc</groupId>
			<artifactId>springdoc-openapi-ui</artifactId>
			<version>1.6.13</version>
>>>>>>> master
```

Onde ele mostra o trecho em conflito entre teu branch e o master.
Neste caso, basta remover as linhas <<<<, ===== e >>>>> inteiras que as duas alterações serão incluídas.
Daí é commit e push.

2022-11-23 18:31 UTC, manoelcampos requested changes
O código está muito bom e bem organizado. Só uns pequenos detalhes.

2022-11-23 18:31 UTC, manoelcampos commented on sistema-locadora-veiculo/src/main/java/br/edu/ifto/sistemalocadoraveiculo/entidades/Cidade.java
> +@Data
Confirmou se o lombok funciona por padrão no IntelliJ community? Só tenho o Ultimate.
Se não funciona, o pessoal não vai conseguir compilar nos labins
sem ter o plugin.

2022-11-23 18:31 UTC, manoelcampos commented on sistema-locadora-veiculo/src/main/java/br/edu/ifto/sistemalocadoraveiculo/entidades/Endereco.java
> +    @JoinColumn(name="cidade_cod", referencedColumnName = "id")
Vamos usar Convention over Configuration (CoC), deixando a JPA decidir o nome dos campos e FKs no banco de dados. Por isso, apenas apaga a anotação JoinColumn.

2022-11-23 18:31 UTC, manoelcampos commented on sistema-locadora-veiculo/src/main/java/br/edu/ifto/sistemalocadoraveiculo/entidades/Cidade.java
> +    @JoinColumn(name="estado_cod", referencedColumnName = "id")
Aqui a mesma coisa que falei sobre JoinColumn abaixo.

2022-11-23 22:19 UTC, manoelcampos commented on sistema-locadora-veiculo/src/main/java/br/edu/ifto/sistemalocadoraveiculo/entidades/Cidade.java
> +@Data
Se não tiver o plugin, o projeto compila pelo terminal, mas o IDE fica mostrando erro pois não reconhece os getters e setters que só existão nas classes compiladas. O dev tbm não consegue usar o auto-completar para chamar estes métodos.

2022-11-24 02:19 UTC, BernardCarvalho commented on sistema-locadora-veiculo/src/main/java/br/edu/ifto/sistemalocadoraveiculo/entidades/Cidade.java
> +@Data
![image](https://user-images.githubusercontent.com/99513042/203679074-b6b5908c-9d58-4200-93f2-919e418b1264.png)

Boa noite professor @manoelcampos, foi feito o teste e na versão 2022.2.4 (Community Edition), o IntelliJ reconhece a anotação @Data do lombok sem nenhum problema

No entanto, essa versão não realizou o carregamento das dependencias que estavam no pom.xml de forma automática, sendo necessário clicar no botão "Load Maven Changes (ctrl+o)" dentro do arquivo pom.xml (mas isso se aplica a todas as dependencias, caso venha a ser um impecilho, imagino que seria mais facil abandonar o uso da IDE do que deixar de usar a ferramenta de build)
![image](https://user-images.githubusercontent.com/99513042/203679577-6f364565-33b2-4711-b936-2d2fe8957254.png)

2022-11-24 02:36 UTC, BernardCarvalho commented on sistema-locadora-veiculo/src/main/java/br/edu/ifto/sistemalocadoraveiculo/entidades/Endereco.java
> +    @JoinColumn(name="cidade_cod", referencedColumnName = "id")
9a8c057271ce72ee7cf6c317e35a6fecb2ab6bd6 - Resolvido neste commit

2022-11-24 02:36 UTC, BernardCarvalho commented on sistema-locadora-veiculo/src/main/java/br/edu/ifto/sistemalocadoraveiculo/entidades/Cidade.java
> +    @JoinColumn(name="estado_cod", referencedColumnName = "id")
20a8fe616dbcb2a9543b65e18b5e694f9eae8b06 - Resolvido neste commit

2022-11-24 12:15 UTC, merged

2022-11-29 01:54 UTC, manoelcampos commented
Lembrei de alguns problemas que podem surgir ao usar `@Data` do Lombok. [Veja este artigo](https://www.jpa-buddy.com/blog/lombok-and-jpa-what-may-go-wrong/).
O ideal é usar `@Getter @Setter` no lugar, mesmo que seja mais extenso.