28 criar entidade classe cliente e relacionadas no sistema aéreo
iftopalmas/sistemas-viagens pull request #49
Opened 2022-11-27 21:43 UTC by nunesvictor

2022-11-28 19:37 UTC, manoelcampos requested changes
So alguns ajustes para padronização.

2022-11-28 19:37 UTC, manoelcampos commented on sistema-companhia-aerea/src/main/java/br/edu/ifto/sistemacompanhiaaerea/model/Cliente.java
> +    @JoinColumn(name = "endereco_id")
Estamos usando CoC, por isso, deixamos a JPA decidir o nome das tabelas no banco e FKs.
Assim, basta remover os `@JoinColumn`

2022-11-28 19:37 UTC, manoelcampos commented on sistema-companhia-aerea/src/main/java/br/edu/ifto/sistemacompanhiaaerea/model/ContatoSeguranca.java
> +@Table(name = "contato_seguranca")
Remover `@Table`  para padronização (CoC)

2022-11-28 19:37 UTC, manoelcampos commented on sistema-companhia-aerea/src/main/java/br/edu/ifto/sistemacompanhiaaerea/model/Endereco.java
> +    @Column(name = "id", nullable = false)
O `@Id` já torna a coluna não nula. Não precisa deste `@Column` inteiro.

2022-11-30 12:45 UTC, nunesvictor commented
Aguardando o merge para dar seguimento em #51

2022-11-30 19:44 UTC, manoelcampos commented
> Aguardando o merge para dar seguimento em #51

Tinha colocado uns comentarios que ficaram sem resolver,veja aí pra darmos prosseguimento.

2022-11-30 19:45 UTC, manoelcampos commented
Vou corrigir pra andar mais rapido.

2022-11-30 19:46 UTC, manoelcampos approved these changes

2022-11-30 19:57 UTC, merged