Configurar plugin do dependabot no build.yml #45
iftopalmas/sistemas-viagens pull request #58
Opened 2022-11-29 00:16 UTC by huan-carlos

2022-11-29 00:26 UTC, manoelcampos requested changes

2022-11-29 00:26 UTC, manoelcampos commented on .github/workflows/build.yml
> +    - name: dependabot_sistema-agencia-viagem
Vc não precisa criar outro workflow. Adiciona o conteúdo da linha 26 até a 35 no final do arquivo maven.yml que já existe. O erro que está ocorrendo no build é porque a action do dependabot (pra analisar falhas de segurança nas dependências dos projetos) não está sendo usado.

Adiciona a linha abaixo antes de cada `run` a partir da linha 26:

```yml
uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
```

2022-11-29 00:27 UTC, manoelcampos commented on .github/workflows/build.yml
> +    - name: dependabot_sistema-agencia-viagem
Isso tá no exemplo de uso da página da action que coloquei na issue.

2022-11-29 00:56 UTC, manoelcampos commented
O problema é a estrutura. O uses do dependabot tá repetido, mas na verdade deve aparecer uma vez só.
Atualmente tá assim:

```yml
- name: dependabot_sistema-agencia-viagem
   uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
   run: maven-dependency-submission -d sistema-agencia-viagem/pom.xml
```

Mas tenta assim:

```yml
- uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
   name: dependabot_sistema-agencia-viagem
   run: |
       maven-dependency-submission -d sistema-agencia-viagem/pom.xml
       maven-dependency-submission -d sistema-companhia-aerea/pom.xml
       e pros outros sistemas aqui
```

2022-11-29 00:58 UTC, manoelcampos commented
Ou tenta colocar o uses do dependabot lá no topo com `- uses: actions/checkout@v3`

2022-11-29 02:46 UTC, manoelcampos commented
A versao é v2.0.1. Tá na pagina da action.

2022-11-29 02:50 UTC, manoelcampos requested changes

2022-11-29 02:50 UTC, manoelcampos commented on pom.xml
> +         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
Apareceu este novo pom.xml e alterações no pom do sistema de agencia de viagens que não deveria existir.
Algo saiu errado no seu último commit, mas hoje não dá mais pra eu ver.

2022-11-29 02:51 UTC, manoelcampos commented on pom.xml
> +         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
As alteracoes deviam ser apenas no xml

2022-11-29 15:47 UTC, huan-carlos commented on pom.xml
> +         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
Estava testando um artigo que li, mas também não funcionou.
Reverti os commits

2022-12-01 12:36 UTC, manoelcampos commented
@huan-carlos o parâmetro -d pede o caminho de um diretório, não o do pom.xml.
Mas de qualquer forma não funcionou. Ele continua executando na raiz do projeto.
Pode ser bug da action ou não estamos sabendo fazer. Na página da action não tem exemplo de uso.
Então, o jeito é criar um arquivo yml para cada sistema mesmo, como `sistema-viagens.yml` e outros 3.

Aí, a configuração da action fica algo como:

```yml
- uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
   with: sistemas-hotelaria
```

2022-12-01 18:28 UTC, manoelcampos commented
É isso. O build ta falhando mas é outra coisa. Valeu.

2022-12-01 18:29 UTC, manoelcampos approved these changes

2022-12-01 18:30 UTC, merged