Issue #54
iftopalmas/sistemas-viagens pull request #66
Opened 2022-11-29 13:53 UTC by DaniloNilo11

Close 54

2022-11-29 14:01 UTC, BernardCarvalho reviewed
Era pra deletar esse arquivo mesmo?

2022-11-29 16:59 UTC, BernardCarvalho requested changes

2022-11-29 16:59 UTC, BernardCarvalho commented on sistema-locadora-veiculo/src/main/java/br/edu/ifto/sistemalocadoraveiculo/entidades/PessoaJuridica.java
> +
De acordo com o descrito na issue #54 , o atributo cnpj da classe PessoaJuridica deve ser do tipo String, e não inteiro

2022-11-29 16:59 UTC, BernardCarvalho commented on sistema-locadora-veiculo/src/main/java/br/edu/ifto/sistemalocadoraveiculo/entidades/PessoaJuridica.java
> +
Não se esquecer de adicionar as notações do atributo também `(@CNPJ @NotBlank @Column(unique=true)`, no fim, você terá algo parecido com:
`@CNPJ`
`@NotBlank`
`@Column(unique=true)`
`private String cnpj;`

2022-11-29 16:59 UTC, BernardCarvalho commented on sistema-locadora-veiculo/src/main/java/br/edu/ifto/sistemalocadoraveiculo/entidades/PessoaJuridica.java
> +
Por gentileza, altere o nome do atributo para manter-se conforme solicitado na issue #54  (`private String razaoSocial;`), de forma que outros desenvolvedores, saberão que este atributo faz referencia ao atributo solicitado na issue.

Também não se esqueça de adicionar a notação que impede que seja validada uma entidade cujo atributo (nome/razaoSocial) seja em branco ("", "   "):
`@NotBlank`

2022-12-01 12:10 UTC, manoelcampos commented
> Era pra deletar esse arquivo mesmo?

Não, eu reverti o commit. Tudo certo.

2022-12-06 00:05 UTC, manoelcampos commented on sistema-locadora-veiculo/src/main/java/br/edu/ifto/sistemalocadoraveiculo/entidades/Locadora.java
> -import lombok.Getter;
É pra usar mesmo as anotações Getter e Setter. Tem uma PR explicando isso. Mas deixa como está, depois a gente corrige aqui e em outros locais.

2022-12-06 00:06 UTC, manoelcampos commented on sistema-locadora-veiculo/src/main/java/br/edu/ifto/sistemalocadoraveiculo/entidades/Locadora.java
> -import lombok.Getter;
Ver último comentário em #38

2022-12-06 00:07 UTC, manoelcampos approved these changes

2022-12-06 00:13 UTC, viniiciusmoura commented on sistema-locadora-veiculo/src/main/java/br/edu/ifto/sistemalocadoraveiculo/entidades/Locadora.java
> -import lombok.Getter;
Beleza.

2022-12-06 00:15 UTC, manoelcampos approved these changes

2022-12-06 00:16 UTC, merged