Issue 64
iftopalmas/sistemas-viagens pull request #68
Opened 2022-11-29 13:56 UTC by lucasTheodoroOliveira

2022-11-29 23:45 UTC, BernardCarvalho requested changes
Boa noite @lucasTheodoroOliveira , não basta remover os metodos getters e setters dos atributos das classes, é necessário adicionar as notações `@Getter` e `@Setter` as classes para que os métodos sejam criados de forma automática pelo Lombok.

2022-11-30 17:36 UTC, lucasTheodoroOliveira commented
Boa tarde Bernard , quem me instruiu a fazer isso , foi o próprio professor
, mas eu posso ajeitar !


Em ter., 29 de nov. de 2022 às 20:45, BernardCarvalho <
***@***.***> escreveu:

> ***@***.**** requested changes on this pull request.
>
> Boa noite @lucasTheodoroOliveira
> <https://github.com/lucasTheodoroOliveira> , não basta remover os metodos
> getters e setters dos atributos das classes, é necessário adicionar as
> notações @Getter e @Setter as classes para que os métodos sejam criados
> de forma automática pelo Lombok.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/iftopalmas/sistemas-viagens/pull/68#pullrequestreview-1198503675>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APAY5XQ4LGVXVKBDI6WKLV3WK2IQXANCNFSM6AAAAAASOQKG3M>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-12-01 12:18 UTC, manoelcampos commented
Bom dia @lucasTheodoroOliveira ,
o que o @BernardCarvalho disse foi que, além de remover os getters e setters, precisa deste passo a mais.
Ele tá contribuindo na revisão do código para agilizar as coisas, faz parte do trabalho em equipe.

2022-12-05 22:26 UTC, manoelcampos commented
@lucasTheodoroOliveira, por falta de comunicação e resolução dos problemas, a PR está sendo assumida por outra pessoa.

@Eduardo-Ozika, você pode ver a conversa na página da PR e verificar o que falta resolver?

Você pode fazer um checkout do branch de nome `issue-22`, fazer as alterações, realizar os commits e fazer push.

2022-12-07 01:24 UTC, manoelcampos approved these changes

2022-12-07 01:25 UTC, manoelcampos commented
> Boa noite @lucasTheodoroOliveira , não basta remover os metodos getters e setters dos atributos das classes, é necessário adicionar as notações `@Getter` e `@Setter` as classes para que os métodos sejam criados de forma automática pelo Lombok.

Resolvido

2022-12-07 01:26 UTC, merged