#59
iftopalmas/sistemas-viagens pull request #69
Opened 2022-11-29 14:19 UTC by HadisBra

Depende de #54

2022-11-30 11:56 UTC, BernardCarvalho requested changes

2022-11-30 11:56 UTC, BernardCarvalho commented on sistema-locadora-veiculo/src/main/java/br/edu/ifto/sistemalocadoraveiculo/entidades/Reserva.java
> +
Conforme informado na issue #59 , é necessário comentar esses atributos até que a issue #54 seja resolvida, pois é responsabilidade da issue 54 definir a classe Locadora, portanto, por gentileza comente os atributos e informe um TODO: depende da issue 54.

Deve ficar algo como:

//TODO: depende da issue 54
//@NotNull
//private  Locadora locadoraRetirada;
//@NotNull
//private  Locadora locadoraDevolucao;

2022-12-01 12:22 UTC, manoelcampos commented on sistema-locadora-veiculo/src/main/java/br/edu/ifto/sistemalocadoraveiculo/entidades/Reserva.java
> +
Exato. @HadisBra , dá uma posição pra gente sobre isso, por favor.

2022-12-01 13:50 UTC, manoelcampos approved these changes
Não cumpriu os requisitos para dataHoraCadastro. Veja no texto da issue.
É preciso incluir o campo id e anotação `@Entity` (não coloquei pois é meio que implícito)

2022-12-01 13:50 UTC, manoelcampos requested changes
Veja último comentário

2022-12-01 21:11 UTC, closed without merging