Resolve 'Criar hierarquia de herança para as classes de Pessoa no sistema aéreo'
iftopalmas/sistemas-viagens pull request #73
Opened 2022-12-02 02:18 UTC by nunesvictor

Closes #51

2022-12-02 13:13 UTC, nunesvictor commented
O posicionamento das anotações faz diferença?

2022-12-02 13:14 UTC, manoelcampos requested changes

2022-12-02 13:14 UTC, manoelcampos commented on sistema-companhia-aerea/src/main/java/br/edu/ifto/sistemacompanhiaaerea/model/Cliente.java
> +    @Getter
`@Getter @Setter` é só uma vez na classe, mas vou alterar aqui.

2022-12-02 13:14 UTC, manoelcampos commented on sistema-companhia-aerea/src/main/java/br/edu/ifto/sistemacompanhiaaerea/model/Piloto.java
> +    @ManyToOne
Aqui é OneToOne: não temos vários pilotos para uma mesma pessoa.

2022-12-02 13:15 UTC, manoelcampos commented
> O posicionamento das anotações faz diferença?

Em alguns casos sim (dependendo da anotação inclusive, nem aceita colocar no lugar errado).
Aqui é só que não precisa duplicar elas em cada atributo. Coloca só uma vez no topo e pronto.

2022-12-02 14:06 UTC, nunesvictor commented on sistema-companhia-aerea/src/main/java/br/edu/ifto/sistemacompanhiaaerea/model/Piloto.java
> +    @ManyToOne
Vacilo, fiz tarde da noite já tava esgotado

2022-12-02 14:11 UTC, manoelcampos commented on sistema-companhia-aerea/src/main/java/br/edu/ifto/sistemacompanhiaaerea/model/Piloto.java
> +    @ManyToOne
🤣

2022-12-02 14:11 UTC, manoelcampos commented on sistema-companhia-aerea/src/main/java/br/edu/ifto/sistemacompanhiaaerea/model/Piloto.java
> +    @ManyToOne
Ainda recebi email na hora, mas eu tava em outra tarefa

2022-12-05 22:00 UTC, manoelcampos requested changes

2022-12-05 22:00 UTC, manoelcampos commented on sistema-companhia-aerea/src/main/java/br/edu/ifto/sistemacompanhiaaerea/model/Piloto.java
> +    @ManyToOne
@nunesvictor faltou essa aqui. Quando terminar, veja se tem permissão para fazer o merge e já faz, por favor.

2022-12-05 22:21 UTC, manoelcampos approved these changes

2022-12-05 22:22 UTC, merged