CLOSE #88
iftopalmas/sistemas-viagens pull request #96
Opened 2022-12-06 14:52 UTC by DaniloNilo11

Close #88

2022-12-07 01:40 UTC, manoelcampos requested changes

2022-12-07 01:40 UTC, manoelcampos commented on sistema-locadora-veiculo/src/main/java/br/edu/ifto/sistemalocadoraveiculo/entidades/CategoriaVeiculo.java
> +    @NotBlank
NotBlank é apenas para atributo String. Para objetos deve ser NotNull

2022-12-07 01:40 UTC, manoelcampos commented on sistema-locadora-veiculo/src/main/java/br/edu/ifto/sistemalocadoraveiculo/entidades/Veiculo.java
> +    public void setId(Long id) {
Não tem getter e setter pois estes são incluídos pelo Lombok.

2022-12-07 01:40 UTC, manoelcampos commented on sistema-locadora-veiculo/src/main/java/repositories/CategoriaVeiculoRepository.java
> +    CategoriaVeiculo findByName(@Param("id")Long id);
este método deveria chamar findById, mas não precisa incluí-lo (pode remover), pois ele é incluído automaticamente pela interface que vc tá estendendo.

2022-12-07 01:40 UTC, manoelcampos commented on sistema-locadora-veiculo/src/main/java/repositories/CategoriaVeiculoRepository.java
> +    CategoriaVeiculo findByName(@Param("descricao")String descricao);
se o nome do campo que está usando na busca é descricao, o nome do método deve chamar findByDescricao

2022-12-10 20:01 UTC, DaniloNilo11 commented on sistema-locadora-veiculo/src/main/java/br/edu/ifto/sistemalocadoraveiculo/entidades/CategoriaVeiculo.java
> +    @NotBlank
Alteração feita

2022-12-10 20:01 UTC, DaniloNilo11 commented on sistema-locadora-veiculo/src/main/java/br/edu/ifto/sistemalocadoraveiculo/entidades/Veiculo.java
> +    public void setId(Long id) {
Alteração feita

2022-12-12 14:25 UTC, manoelcampos requested changes
Vão não fez push de qualquer alteração.

2022-12-13 13:52 UTC, manoelcampos approved these changes

2022-12-13 13:53 UTC, merged